query postSummaries {
  postConnection {
    edges {
      node {
        title
        summary
        publishedOn
        readingTime
        thumbnail
        slug
        author {
          ... on Author {
            name
            avatar
          }
        }
      }
    }
  }
}
